### ISSUE TITLE
Mismatched deps

### ISSUE THREAD

**Issue by gorlins** [conda-forge/celery-feedstock#1]
Dependencies here for v 3.2.23 request:

    - billiard >=3.3.0.22,<3.4
    - kombu >=3.0.33,<4.0

But the setup.py wants:

    billiard>=3.3.0.23,<3.4
    kombu>=3.0.34,<3.1

Celery changelog explicitly mention these newer versions are required, but since they are not available on conda, is this safe to install at all?

**Comment by kwilcox** [comment]
Good question. I've been using this in production for months (it was ported from another conds recipe) without problems when using redis as a broker.  I can imagine the kombu version requirements may depend of on the transport type.

I can take a look next week.

**Comment by gorlins** [comment]
I wonder if @ask is involved with conda?

**Comment by kwilcox** [comment]
@gorlins is it picking up the correct versions (they are in conda-forge). I'll PR a version bump for completeness sake.

```
$ conda install -c conda-forge celery
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/kwilcox/miniconda3/envs/csw_overlord:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ncurses-5.9                |                7         1.0 MB
    sqlalchemy-1.0.13          |           py35_0         1.4 MB
    ------------------------------------------------------------
                                           Total:         2.4 MB

The following NEW packages will be INSTALLED:

    amqp:            1.4.9-py35_0   
    anyjson:         0.3.3-py35_0   
    billiard:        3.3.0.23-py35_1
    ca-certificates: 2016.2.28-0    
    celery:          3.1.23-py35_0  
    kombu:           3.0.33-py35_0  
    ncurses:         5.9-7          
    pytz:            2016.4-py35_0  
    sqlalchemy:      1.0.13-py35_0
```

**Comment by kwilcox** [comment]
Actually, `kombu` needs to be bumped!

**Comment by gorlins** [comment]
kombu and billiard both need bumping to comply with the upstream setup.py

**Comment by kwilcox** [comment]
Fixed in https://github.com/conda-forge/celery-feedstock/pull/3/commits/e53fac55f9d40a70407922867ce55870b4f558db, just waiting for CI
