### ISSUE TITLE
Current version fails pip-check

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/celery-feedstock#31]
Looks like a touch of dependency drift:

```
+ python -m pip check
celery 4.4.0 has requirement billiard<4.0,>=3.6.1, but you have billiard 3.6.0.0.
```

Blocked by https://github.com/conda-forge/billiard-feedstock/pull/28

**Comment by mcs07** [comment]
Looking at https://github.com/celery/celery/blob/master/requirements/default.txt

We should probably update both the billiard and kombu pins in this celery recipe to something like:

```
- billiard >=3.6.1,<4.0
- kombu >=4.6.7,<4.7
```

Well, at least the min versions. I don't know how strict we need to be about the max versions?

The kombu recipe already up to date, so we are only waiting on that billiard PR.
