### ISSUE TITLE
version bump to 4.x

### ISSUE THREAD

**Issue by wseaton** [conda-forge/celery-feedstock#6]
Hey there, is it possible to get a version bump to Celery 4.x? 

Looks like the dependency versions have changed based on the requirements/default.txt, specifically for kombu:
```
pytz>dev
billiard>=3.5.0.2,<3.6.0
kombu>=4.0.2,<5.0
```

**Comment by kwilcox** [comment]
Yes of course. Would be great if you could send a PR. Could you also create a branch for the 3.1.x series if you know they are going to backport bugfixes? I have a hard time following celery and its dependent versions.
